#!/usr/bin/env python3
"""
valuation-modeler · Excel workbook export (openpyxl).

Sheets: Cover / Assumptions (with provenance) / DCF Model / Sensitivity
(conditional fill) / Comps. Values only — no formulas — so output is
deterministic and round-trip testable. Missing openpyxl degrades gracefully
(stderr warning, returns None, caller keeps rc=0 with xlsx_skipped=true).
"""
from __future__ import annotations

import sys
from pathlib import Path

HEADER_FILL = "1F4E79"   # dark blue
HEADER_FONT = "FFFFFF"
GOOD_FILL = "C6EFCE"     # sensitivity: above current price
BAD_FILL = "FFC7CE"      # below current price
SELF_FILL = "FFF2CC"     # subject row highlight in comps


def _styles():
    from openpyxl.styles import Alignment, Font, PatternFill
    return {
        "h_font": Font(bold=True, color=HEADER_FONT),
        "h_fill": PatternFill("solid", fgColor=HEADER_FILL),
        "bold": Font(bold=True),
        "center": Alignment(horizontal="center"),
        "good": PatternFill("solid", fgColor=GOOD_FILL),
        "bad": PatternFill("solid", fgColor=BAD_FILL),
        "self": PatternFill("solid", fgColor=SELF_FILL),
    }


def _header_row(ws, row, values, st):
    for col, v in enumerate(values, start=1):
        c = ws.cell(row=row, column=col, value=v)
        c.font, c.fill, c.alignment = st["h_font"], st["h_fill"], st["center"]


def _autowidth(ws, max_w=28):
    for col_cells in ws.columns:
        w = max((len(str(c.value)) for c in col_cells if c.value is not None), default=0)
        ws.column_dimensions[col_cells[0].column_letter].width = min(max(w + 2, 8), max_w)


def _sheet_cover(wb, st, dcf_json, comps_json):
    ws = wb.active
    ws.title = "Cover"
    src = dcf_json or comps_json
    ws.cell(row=1, column=1, value=f"{src['ticker']} · Valuation Model").font = st["bold"]
    rows = [("As of", src["asof"]), ("Generated by", "valuation-modeler (deterministic engine)")]
    if dcf_json:
        rows += [("DCF fair value / share", dcf_json.get("fair_value_per_share")),
                 ("Current price", dcf_json.get("current_price")),
                 ("Upside %", dcf_json.get("upside_pct")),
                 ("WACC used", (dcf_json.get("dcf") or {}).get("wacc_used")),
                 ("Terminal growth used", (dcf_json.get("dcf") or {}).get("terminal_growth_used"))]
    if comps_json:
        rows += [("Comps implied value", comps_json.get("comps_implied_value")),
                 ("Peers used", (comps_json.get("universe") or {}).get("peer_count_used"))]
    for i, (k, v) in enumerate(rows, start=3):
        ws.cell(row=i, column=1, value=k).font = st["bold"]
        ws.cell(row=i, column=2, value=v)
    _autowidth(ws)


def _sheet_assumptions(wb, st, dcf_json):
    ws = wb.create_sheet("Assumptions")
    _header_row(ws, 1, ["Assumption", "Value", "Provenance"], st)
    for i, (k, f) in enumerate((dcf_json.get("assumptions") or {}).items(), start=2):
        ws.cell(row=i, column=1, value=k)
        ws.cell(row=i, column=2, value=f.get("value"))
        ws.cell(row=i, column=3, value=f.get("provenance"))
    _autowidth(ws)


def _sheet_dcf(wb, st, dcf_json):
    ws = wb.create_sheet("DCF Model")
    d = dcf_json.get("dcf") or {}
    cols = ["Year", "Growth", "Revenue", "EBITDA", "EBIT", "NOPAT", "Capex", "ΔNWC", "FCFF", "PV FCFF"]
    _header_row(ws, 1, cols, st)
    keys = ["year", "growth", "revenue", "ebitda", "ebit", "nopat", "capex", "d_nwc", "fcff", "pv_fcff"]
    r = 2
    for row in d.get("fcff_table", []):
        for col, k in enumerate(keys, start=1):
            ws.cell(row=r, column=col, value=row.get(k))
        r += 1
    r += 1
    for label, key in [("PV explicit", "pv_explicit"), ("PV terminal", "pv_terminal"),
                       ("Enterprise value", "enterprise_value"), ("Net debt", "net_debt"),
                       ("Equity value", "equity_value"), ("Shares (diluted)", "shares"),
                       ("Fair value / share", None)]:
        ws.cell(row=r, column=1, value=label).font = st["bold"]
        ws.cell(row=r, column=2,
                value=dcf_json.get("fair_value_per_share") if key is None else d.get(key))
        r += 1
    for w in d.get("warnings", []):
        ws.cell(row=r, column=1, value=f"⚠ {w}")
        r += 1
    _autowidth(ws)


def _sheet_sensitivity(wb, st, dcf_json):
    ws = wb.create_sheet("Sensitivity")
    s = dcf_json.get("sensitivity") or {}
    tgs, waccs, grid = s.get("terminal_growth_values", []), s.get("wacc_values", []), s.get("grid", [])
    if not grid:
        ws.cell(row=1, column=1, value="(sensitivity unavailable — DCF degraded)")
        return
    price = dcf_json.get("current_price")
    _header_row(ws, 1, ["WACC \\ g"] + [f"{g:.2%}" for g in tgs], st)
    for i, (w, row) in enumerate(zip(waccs, grid), start=2):
        ws.cell(row=i, column=1, value=f"{w:.2%}").font = st["bold"]
        for j, v in enumerate(row, start=2):
            c = ws.cell(row=i, column=j, value=v)
            if isinstance(v, (int, float)) and isinstance(price, (int, float)):
                c.fill = st["good"] if v >= price else st["bad"]
    ws.cell(row=len(waccs) + 3, column=1,
            value=f"Green ≥ current price ${price} · Red < current price")
    _autowidth(ws)


def _sheet_comps(wb, st, comps_json):
    ws = wb.create_sheet("Comps")
    u = comps_json.get("universe") or {}
    _header_row(ws, 1, ["Ticker", "Name", "Mkt Cap ($B)", "P/E", "EV/EBITDA",
                        "EV/Sales", "EPS g fwd", "PEG"], st)

    def _write(r, sym, p, highlight=False):
        vals = [sym, p.get("name"),
                round(p["market_cap"] / 1e9, 1) if p.get("market_cap") else None,
                p.get("pe"), p.get("ev_ebitda"), p.get("ev_sales"),
                p.get("eps_growth_fwd"), p.get("peg")]
        for col, v in enumerate(vals, start=1):
            c = ws.cell(row=r, column=col, value=v)
            if highlight:
                c.fill = st["self"]

    r = 2
    s = u.get("self") or {}
    _write(r, s.get("symbol"), s, highlight=True)
    r += 1
    for sym, p in (u.get("peers") or {}).items():
        _write(r, sym, p)
        r += 1

    r += 1
    _header_row(ws, r, ["Metric", "n", "Q1", "Median", "Q3", "Self", "Implied $"], st)
    r += 1
    for m, row in (comps_json.get("table") or {}).get("metrics", {}).items():
        q = row.get("quartiles") or {}
        for col, v in enumerate([m, row.get("n"), q.get("q1"), q.get("median"),
                                 q.get("q3"), row.get("self_value"), row.get("implied_value")], start=1):
            ws.cell(row=r, column=col, value=v)
        r += 1
    ws.cell(row=r + 1, column=1, value="comps_implied anchor").font = st["bold"]
    ws.cell(row=r + 1, column=2, value=comps_json.get("comps_implied_value"))
    _autowidth(ws)


def build_workbook(dcf_json: dict | None, comps_json: dict | None, out_path: str) -> str | None:
    """Write workbook; returns path or None when openpyxl is unavailable."""
    try:
        from openpyxl import Workbook
    except ImportError:
        print("WARN: openpyxl not installed — xlsx export skipped (pip install openpyxl)",
              file=sys.stderr)
        return None
    if not (dcf_json or comps_json):
        return None
    st = _styles()
    wb = Workbook()
    _sheet_cover(wb, st, dcf_json, comps_json)
    if dcf_json:
        _sheet_assumptions(wb, st, dcf_json)
        _sheet_dcf(wb, st, dcf_json)
        _sheet_sensitivity(wb, st, dcf_json)
    if comps_json:
        _sheet_comps(wb, st, comps_json)
    p = Path(out_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(p))
    return str(p)
